### ISSUE TITLE
Find and remove unused / duplicated code

### ISSUE THREAD

**Issue by johannesduesing** [delphi-hub/delphi-registry#103]
**Describe the problem**
Some of the source code of the registry has been introduced a while ago, but is not actually used or the feature has been changed. Some examples are:

- The ```ErrorLog``` property when reporting failure
- The huge number of switches that can be set for ```executeCommand```

**Describe the solution you would like**
Go through the codebase of the registry, identify and remove unused code. It may be helpful to run the tests with coverage to see which parts of the code are not being executed.

**Comment by 24santoshr** [comment]
closed by #107
