### ISSUE TITLE
Test docker deployment

### ISSUE THREAD

**Issue by johannesduesing** [delphi-hub/delphi-registry#104]
**Describe the problem**
When users want to run the registry inside a docker container, the configuration settings may need to be applied in a different way than when it is run directly on the machine. This is due to the networking configurations of docker itself. There is no concrete issue yet, but i've run into some trouble trying this lately.

**Describe the solution you would like**
Try to setup a full Delphi system with the registry running inside its own docker container. Document every step that you had to take in order to make the setup work, and describe them in the README file.

**Comment by johannesduesing** [comment]
I did a setup of the registry in Docker on our deployment server, and it worked pretty well. The main thing to keep in mind is that the Docker host now cannot be ```localhost:9095``` anymore, and that every networking URI has to be seen from the perspective of a Docker container. If you agree with those findings @24santoshr, can you please add a hint for that to the README and close this issue ?

**Comment by 24santoshr** [comment]
closed by #108
