### ISSUE TITLE
Add a "Quickstart" guide to readme

### ISSUE THREAD

**Issue by johannesduesing** [delphi-hub/delphi-registry#109]
**Describe the problem**
We have a quite long readme file, which contains a lot of information regarding every possible deployment scenario. Since we are getting more and more questions from frontend-users on why their setup is not working as expected, it might be a good idea to collect all information necessary for a quick registry setup in one place.

**Describe the solution you'd like**
Add a *Getting Started* or *Quickstart* section to the readme, where only the steps and settings needed for a minimal working deployment scenario are collected.

**Comment by 24santoshr** [comment]
Closed by #118
