### ISSUE TITLE
Analyze CI race condition

### ISSUE THREAD

**Issue by johannesduesing** [delphi-hub/delphi-registry#110]
**Describe the problem**
There is a strange race condition that causes many of our Travis CI builds to fail with message
```
java.lang.IllegalStateException: cannot create children while terminating or terminated
```
Mostly this can be fixed by restarting the build, but we should look for a way to fix this issue. It seems to be due to the fact that a test tries to access an ActorSystem that is already closed. Note that this did not happen once on any developer machine, only in the Travis CI builds.

**Describe the solution you would like**
Analyze our ActorSystem usage and find a possible cause for the race condition. If it turns out to be a Travis problem that's fine as well, but try to find an error on our side first.

**Comment by 24santoshr** [comment]
closed by #111
