### ISSUE TITLE
Refactor README

### ISSUE THREAD

**Issue by johannesduesing** [delphi-hub/delphi-registry#117]
**Describe the problem**
Our README file is getting longer and quite hard to understand, as it contains all configuration switches that exist. It is not obvious to the user what parts of the file are needed and what parts are optional.

**Describe the solution you would like**
Refactor the README file. Use a more use-case oriented approach. Starting with the quickstart guide ( #109 ) which explains a minimal setup, use sections to expand this setup with additional features like
* Use SQL databases
* Use different machines for Docker Host and Registry Hosts
* Run the registry inside of Docker
* Use and re-configure Traefik

**Comment by 24santoshr** [comment]
Referring #132

**Comment by johannesduesing** [comment]
Closed with #132
