### ISSUE TITLE
Deal with non-state changes to instances

### ISSUE THREAD

**Issue by johannesduesing** [delphi-hub/delphi-registry#119]
**Describe the problem**
When the state of an instance changes, we sent a ```StateChangedEvent``` which is caught by the management backend to update data without reloading a page.
Now that their team started the implementation for adding a label to instances, it turns out that we also need an event being triggered by this operation, so that they can immediately show the newly added label without reloading the page.

**Describe the solution you would like**
I see two possible solutions to this problem. We either introduce a ```LabelAddedEvent``` and raise it whenever a label is added successfully, or we change the ```StateChangedEvent``` to be a more generic ```InstanceModifiedEvent```, which would be raised whenever something related to an instance changes.

**Comment by johannesduesing** [comment]
I talked abot this with @janniclas and we decided to keep the name ```StateChangedEvent```, for the sake of backwards-compability (the name is used for event parsing).

**Comment by 24santoshr** [comment]
Closed by #124
