### ISSUE TITLE
Provide a way to delete a Label

### ISSUE THREAD

**Issue by johannesduesing** [delphi-hub/delphi-registry#126]
**Describe the problem**
It is currently possible to add labels to instances, but not to remove them.

**Describe the solution you'd like**
Add an endpoint that enables users to delete a certain label. *May* look like this:
```
DELETE /instances/{InstanceId}/labels/{LabelName}
```

**Comment by sami-cseseu** [comment]
The route will be like `DELETE /instances/{InstanceId}/label/{LabelName}`

**Comment by johannesduesing** [comment]
Closed with #128
