### ISSUE TITLE
Write a Docker API client

### ISSUE THREAD

**Issue by johannesduesing** [delphi-hub/delphi-registry#21]
The instance registry will need to call the Docker API for operations like deploy, start, stop, etc.. We need to write a client API that calls the Docker HTTP API and provides the following operations:
- deploy(string InstanceName, string IRHost, int IRPort, ComponentType type) : Try[containerId]
- pause / resume / stop / start / delete(containerId) : Boolean
- isContainerIdPresent(containerId) : Boolean
- getInfo(containerId): ???

**Comment by 24santoshr** [comment]
Referring #27

**Comment by johannesduesing** [comment]
Closed with #27
