### ISSUE TITLE
Introduce branch system to match gitflow workflow

### ISSUE THREAD

**Issue by janniclas** [delphi-hub/delphi-registry#4]
Since we follow the gitflow workflow in every delphi project, we should create a branch structure to match this in this git too. So we should mark the master and develop (after it has been created) as protected branches and create the merge requests to the develop branch.

**Comment by 24santoshr** [comment]
I have created 'develop' branch and added protection rules to both develop and master. Please let me know if I have missed anything.

**Comment by janniclas** [comment]
looks good to me. 
I will close this for now, thanks for the work :)
@bhermann since you are the main maintainer of the delphi gits feel free to reopen this issue and add further suggestions if you feel like we missed anything.
