### ISSUE TITLE
Bad exception handling for malformed JSON input

### ISSUE THREAD

**Issue by johannesduesing** [delphi-hub/delphi-registry#50]
When calling ```POST /register``` with an JSON entity that has valid JSON syntax but is missing required members, the registry will correctly respond with a ```400 Bad Request``` response containing an message hinting the malformed input.
However, if the JSON *syntax* is invalid (missing quotation mark or similar), the response will be ```500 Internal Server Error``` without any further information.
The reason for this is that the registry will catch ```DeserializationException``` separately  and produce the Bad Request response, but not ```ParsingExceptions```, which are treated like any general exception, and therefore produce an Internal Server Error.

**Desired Behaviour**
All errors caused by malformed input data should be handled with ```400 Bad Request``` and an appropriate error message.

**Comment by 24santoshr** [comment]
Fixed by #51. Hence closing the issue
