### ISSUE TITLE
Error when running Registry Docker image

### ISSUE THREAD

**Issue by 24santoshr** [delphi-hub/delphi-registry#59]
The below message  pops up when building the registry docker image and  running it. 
env: can't execute 'bash': No such file or directory.

**Comment by 24santoshr** [comment]
On investigation it was found that this error is due the alpine plugin used in build.sbt file inside registry. Commenting the plugin usage will build  and run the image successfully.

@sami-cseseu and @johannesduesing : Could you guys please build the latest registry code as docker image and run it as a container. Just want to check whether the error is caused by my system configuration or a general one.

**Comment by bhermann** [comment]
alpine linux does not ship with bash. However, the image is comfortably small so I would hesitate going to a larger image. Do you really need bash or could you cope with the installed `/bin/sh` ?

**Comment by 24santoshr** [comment]
I think /bin/sh should be fine for now. Probably when registry becomes large enough we can go for alpine.

**Comment by 24santoshr** [comment]
Referencing #71
