### ISSUE TITLE
Adapt the HTTP tests to new API

### ISSUE THREAD

**Issue by johannesduesing** [delphi-hub/delphi-registry#81]
**Describe the problem**
Since we specified a new HTTP API for the registry (see #57), which is currently being implemented, we also have to adapt the entire HTTP tests to the new URI schemas.

**Describe the solution you would like**
Adapt the existing tests. The functionality will stay the same, only the uri and parameter format will need to be changed.

**Comment by 24santoshr** [comment]
Referring #90

**Comment by johannesduesing** [comment]
Closed with #90
