### ISSUE TITLE
Mac Config

### ISSUE THREAD

**Issue by janniclas** [delphi-hub/delphi-registry#84]
**Mac settings Documentation**
`Set   val uriInLocalNetwork: String = "http://host.docker.internal:8087"`
Sometimes akka uses the ipv6 adresses to bind the registry, which won't work with the docker host, so add  export `_JAVA_OPTIONS="-Djava.net.preferIPv4Stack=true" `to make sure the ipv4 address format is used.
And expose the tcp port 
`docker run -d -v /var/run/docker.sock:/var/run/docker.sock -p 127.0.0.1:1234:1234 bobrik/socat TCP-LISTEN:1234,fork UNIX-CONNECT:/var/run/docker.sock`

**Comment by johannesduesing** [comment]
We should probably add the relevant configuration settings to our README file, so mac users can read a full setup tutorial there. This will be done for v0.9.0.

**Comment by 24santoshr** [comment]
Resolved by #92.
