### ISSUE TITLE
Harmonize logging output 

### ISSUE THREAD

**Issue by johannesduesing** [delphi-hub/delphi-registry#91]
**Describe the problem**
Currently the registry outputs lots of duplicated log messages (for example when applying a matching result), and uses the ```INFO``` log level for very detailed information that would normaly go into a ```TRACE``` or ```DEBUG``` level. Also the ```WARN``` level is used for messages which are not really relevant to the user (e.g. when matching to an instance).

**Describe the solution you would like**
Go through each of the endpoints in the registry and harmonize the logging output. This contains:
- Remove duplicated messages
- Put information that is only relevant to the programmers into the ```DEBUG``` level
- Put information that is part of the normal program execution into the ```INFO``` level
- Put information about unexpected events that *do not terminate* the application into the ```WARN``` level (e.g. when an instance was not found, state was invalid, etc). These events are mostly caused by invalid data supplied by the clients.
- Put information about errors into the ```ERROR``` level. Errors are events that cause the registry to stop, and are *not* caused by malformed data supplied by the clients.

**Comment by 24santoshr** [comment]
Referring #100

**Comment by johannesduesing** [comment]
Closed with #100
