### ISSUE TITLE
Confusing link states for not reachable instances

### ISSUE THREAD

**Issue by janniclas** [delphi-hub/delphi-registry#94]
**Feature/Improvement**
If an instance becomes unreachable after successfully being assigned to another instance, the link state is not updated but listed as assigned in both components (the unreachable one and the one it was connected to). In my opinion the correct thing to do would be to update the linkstate to outdated since we can't know anything about this connection without reaching the instance.

**Comment by 24santoshr** [comment]
Referring #122

**Comment by johannesduesing** [comment]
Closed with #122
