### ISSUE TITLE
Error handling after future timeout

### ISSUE THREAD

**Issue by janniclas** [delphi-hub/delphi-registry#96]
If an instance times out during startup (future timeout) we get a strange behavior. The instance has been added to the database successfully but timed out during connection to the docker host. But nonetheless the instance was not removed afterwards and was reported with state deploying to the management application

**Comment by johannesduesing** [comment]
I'm currently not able to reproduce this, thus moving it to the next milestone.

**Comment by 24santoshr** [comment]
Referring #131

**Comment by johannesduesing** [comment]
Closed with #131
